**Example 4.8.** Classify emails represented by the following binary term-to-document vectors as "spam" and "not spam":

|                     | "and" | "offer" | "the" | "of" | "sale" | $y_i$           |
| -                   |  -    |       - | -     |  -   |  -     |  -              |
|                     |       |         |       |      |        |                 |
| $\mathbf{\hat x}_1$ | 1     | 1       | 0     | 1    | 1      | $+1$ (spam)     |
| $\mathbf{\hat x}_2$ | 0     | 0       | 1     | 1    | 0      | $-1$ (not spam) |
| $\mathbf{\hat x}_3$ | 0     | 1       | 1     | 0    | 0      | $+1$ (spam)     |
| $\mathbf{\hat x}_4$ | 1     | 0       | 0     | 1    | 0      | $-1$ (not spam) |
|                     |       |         |       |      |        |                 |  
| $\mathbf{\hat x}_5$ | 1     | 0       | 1     | 0    | 1      | $+1$ (spam)     |
| $\mathbf{\hat x}_6$ | 1     | 0       | 1     | 1    | 0      | $-1$ (not spam) |


In [2]:
import numpy as np
#               AND OFFER THE  OF SALE
Xh = np.array([[ 1 ,  1 ,  0 , 1 , 1],   # x_1   spam
               [ 0 ,  0 ,  1 , 1 , 0],   # x_2   not spam
               [ 0 ,  1 ,  1 , 0 , 0],   # x_3   spam
               [ 1 ,  0 ,  0 , 1 , 0],   # x_4   not spam
               [ 1 ,  0 ,  1 , 0 , 1],   # x_5   spam
               [ 1 ,  0 ,  1 , 1 , 0]    # x_6   not spam
             ])
y = np.array([1,-1,1,-1,1,-1])
X = np.insert(Xh, 0, 1.0, axis=1) # Affine -> Homogeneous form
X

array([[1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0]])

In [3]:
def Perceptron(X,y,K=100):
    theta = np.zeros(X.shape[1])
    k = 0
    while(k<K):
        for i in range(y.size):
            if y[i] * np.dot(X[i], theta) <= 0:
                k += 1
                theta += y[i] * X[i]
                print(k)
        if np.all(y * (X @ theta) > 0):
            break
    return theta

In [8]:
theta = Perceptron(X[:4],y[:4])
theta

1
2
3
4


array([ 0.,  0.,  2.,  0., -1.,  1.])

In [9]:
np.sign(X @ theta) - y

array([0., 0., 0., 0., 0., 0.])